In [1]:
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv('./digit-recognizer/train.csv')
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [3]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten

2023-10-22 12:22:27.317708: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
y = train['label']

In [5]:
y.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [6]:
x = train.drop(['label'],axis=1)
x.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [13]:
classifier = Sequential()


classifier.add(Dense(units=128, input_dim=784, kernel_initializer='uniform', activation='relu'))
classifier.add(Dense(units=28, kernel_initializer='uniform', activation='relu'))
classifier.add(Dense(units=10, kernel_initializer='uniform', activation='softmax'))



classifier.compile(loss="sparse_categorical_crossentropy",optimizer="Adam",metrics=["accuracy"])



In [16]:


history=classifier.fit(x,y,epochs=15,validation_split=0.2)



Epoch 1/15
1050/1050 [==============================] - 23s 22ms/step - loss: 0.0851 - accuracy: 0.9755 - val_loss: 0.1435 - val_accuracy: 0.9643
Epoch 2/15
1050/1050 [==============================] - 25s 24ms/step - loss: 0.0731 - accuracy: 0.9782 - val_loss: 0.1819 - val_accuracy: 0.9607
Epoch 3/15
1050/1050 [==============================] - 23s 22ms/step - loss: 0.0715 - accuracy: 0.9791 - val_loss: 0.1713 - val_accuracy: 0.9620
Epoch 4/15
1050/1050 [==============================] - 24s 23ms/step - loss: 0.0660 - accuracy: 0.9801 - val_loss: 0.1820 - val_accuracy: 0.9611
Epoch 5/15
1050/1050 [==============================] - 22s 21ms/step - loss: 0.0619 - accuracy: 0.9837 - val_loss: 0.1607 - val_accuracy: 0.9648
Epoch 6/15
1050/1050 [==============================] - 19s 18ms/step - loss: 0.0564 - accuracy: 0.9835 - val_loss: 0.1823 - val_accuracy: 0.9630
Epoch 7/15
1050/1050 [==============================] - 21s 20ms/step - loss: 0.0550 - accuracy: 0.9851 - val_loss: 0.1934 -

In [17]:
test = pd.read_csv('./digit-recognizer/test.csv')

In [24]:
y_pr = classifier.predict(test)
y_pr

875/875 [==============================] - 11s 12ms/step


array([[4.9185187e-20, 1.8784407e-18, 1.0000000e+00, ..., 8.3296705e-14,
        8.6743101e-23, 3.8355271e-30],
       [1.0000000e+00, 2.5733269e-27, 1.6312536e-16, ..., 3.4416901e-21,
        1.5308470e-19, 1.3670135e-25],
       [7.3687218e-14, 2.6381383e-15, 1.3351153e-13, ..., 4.8192141e-11,
        7.6486594e-06, 9.9999225e-01],
       ...,
       [0.0000000e+00, 1.5574096e-37, 3.4771007e-26, ..., 0.0000000e+00,
        1.8449561e-26, 1.8458849e-19],
       [3.7025827e-13, 5.6050120e-10, 7.4145223e-10, ..., 2.0237574e-06,
        4.1982228e-05, 9.9992847e-01],
       [8.9539595e-13, 3.0354110e-13, 1.0000000e+00, ..., 1.1428559e-10,
        1.9349590e-14, 4.2679072e-20]], dtype=float32)

array([4.9185187e-20, 1.8784407e-18, 1.0000000e+00, 4.2853375e-13,
       6.1281329e-28, 6.6404203e-26, 9.0542232e-16, 8.3296705e-14,
       8.6743101e-23, 3.8355271e-30], dtype=float32)

In [26]:
predicted_labels = np.argmax(y_pr, axis=1)

In [35]:
predicted_labels

array([2, 0, 9, ..., 3, 9, 2])

In [37]:
predicted_labels_df = pd.DataFrame({'Label': predicted_labels})

# Display the DataFrame
print(predicted_labels_df)

       Label
0          2
1          0
2          9
3          9
4          3
...      ...
27995      9
27996      7
27997      3
27998      9
27999      2

[28000 rows x 1 columns]


In [39]:
predicted_labels_df['ImageId'] = range(1, len(predicted_labels_df) + 1)


print(predicted_labels_df)


       Label  ImageId
0          2        1
1          0        2
2          9        3
3          9        4
4          3        5
...      ...      ...
27995      9    27996
27996      7    27997
27997      3    27998
27998      9    27999
27999      2    28000

[28000 rows x 2 columns]


In [40]:
predicted_labels_df = predicted_labels_df[['ImageId', 'Label']]

In [41]:
predicted_labels_df.to_csv("submission.csv", index=False)