In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

2023-10-22 22:01:04.893652: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
import nltk 
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer



from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import re

[nltk_data] Downloading package stopwords to /home/omkar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
df = pd.read_csv('Twitter_Data.csv',
                 encoding = 'latin',header=None)
df.head()
df = df.dropna()
df.head()

0         1
0                                         clean_text  category
1  when modi promised “minimum government maxim...        -1
2  talk all the nonsense and continue all the dra...         0
3  what did just say vote for modi  welcome bjp t...         1
4  asking his supporters prefix chowkidar their n...         1

In [4]:
# X = df.iloc[1:10,0]
# y = df.iloc[1:10,1]

import re

def clean_text(text):
    # Remove non-ASCII characters
    cleaned_text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    # Remove digits
    cleaned_text = re.sub(r'\d', '', cleaned_text)
    return cleaned_text
df.iloc[1:,0] = df.iloc[1:,0].apply(lambda x: clean_text(x) if isinstance(x, str) else x)


# Drop rows with NaN values
# X = X.dropna()
# y = y.dropna()



X_train, X_test, y_train, y_test = train_test_split(df.iloc[1:500,0], df.iloc[1:500,1],stratify=df.iloc[1:500,1], test_size=0.2, random_state=42)

In [5]:
print(y_train.value_counts())
print(y_test.value_counts())

1     167
0     150
-1     82
Name: 1, dtype: int64
1     42
0     37
-1    21
Name: 1, dtype: int64


In [6]:

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
vectorizer = TfidfVectorizer(stop_words=stopwords.words('english'))
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)
print(X_train_tfidf.shape)
from sklearn.decomposition import TruncatedSVD

# Initialize TruncatedSVD with the desired number of components
n_components = 500  # You can adjust this number as needed
svd = TruncatedSVD(n_components=n_components)

# Fit and transform X_train_tfidf
X_train_svd = svd.fit_transform(X_train_tfidf)
X_test_svd = svd.transform(X_test_tfidf)

(399, 2581)


In [8]:
X_train_svd.shape

(399, 399)

In [9]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_tfidf, y_train)

y_pred = knn.predict(X_test_tfidf)

In [ ]:

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          -1       0.68      0.06      0.11       217
           0       0.39      0.98      0.56       359
           1       0.86      0.18      0.30       424

    accuracy                           0.44      1000
   macro avg       0.64      0.41      0.32      1000
weighted avg       0.65      0.44      0.35      1000



In [ ]:

from sklearn.metrics import confusion_matrix

# Compute the confusion matrix
confusion_mat = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix:")
print(confusion_mat)

Confusion Matrix:
[[ 13 197   7]
 [  2 351   6]
 [  4 343  77]]


In [ ]:
y_pred

array(['0', '1', '0', '-1', '0', '1', '0', '0', '0', '0', '0', '1', '0',
       '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0',
       '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '-1', '0', '0', '0',
       '-1', '0', '-1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0'

In [ ]:
y_test_array = y_test.values

In [ ]:
y_test_array

array(['0', '1', '0', '-1', '1', '1', '1', '1', '-1', '1', '-1', '1',
       '-1', '1', '1', '1', '0', '1', '1', '-1', '0', '0', '0', '0', '0',
       '1', '1', '0', '0', '1', '0', '1', '-1', '0', '1', '0', '1', '1',
       '1', '-1', '1', '-1', '-1', '1', '-1', '0', '1', '1', '0', '0',
       '-1', '1', '1', '0', '-1', '1', '0', '-1', '1', '0', '1', '-1',
       '0', '0', '1', '0', '-1', '1', '1', '0', '1', '1', '-1', '-1',
       '-1', '0', '0', '1', '-1', '-1', '1', '0', '0', '1', '0', '1', '1',
       '0', '0', '0', '1', '1', '0', '0', '-1', '1', '1', '1', '0', '1',
       '1', '-1', '0', '1', '0', '1', '1', '-1', '-1', '1', '1', '-1',
       '-1', '1', '-1', '0', '1', '1', '1', '1', '-1', '0', '-1', '0',
       '0', '0', '1', '1', '0', '0', '0', '-1', '1', '0', '1', '1', '0',
       '0', '-1', '-1', '1', '-1', '1', '-1', '0', '-1', '-1', '0', '-1',
       '1', '1', '0', '1', '1', '-1', '1', '-1', '1', '-1', '0', '1', '1',
       '0', '0', '1', '1', '0', '0', '0', '0', '1', '1', '1